### ISSUE TITLE
yay: error while loading shared libraries: libalpm.so.14: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ChangqingW** [Jguer/yay#2502]
### Affected Version
12.3.5 (commit 02b6d8096ff282f183b6b8c474581a0120c57b4a)
(Cannot run `yay -V` due to the error)

### Describe the bug
Running `yay`gave me the following error message:
`yay: error while loading shared libraries: libalpm.so.14: cannot open shared object file: No such file or directory`

### Reproduction Steps
1. Installing / updating via
```
git clone https://aur.archlinux.org/yay-bin.git
cd yay-bin
makepkg -si
```
2. Run `yay`

### Expected behavior
`yay` updates packages.

### Output
```
❯ yay -V
yay: error while loading shared libraries: libalpm.so.14: cannot open shared object file: No such file or directory
```

**Comment by pdenapo** [comment]
This happened to me after an upgrade of pamac

**Comment by arahiko-ayami** [comment]
It seem a major version of `libalpm` was upgraded and broke the dependency. Temporary fix:
```
sudo ln -s /usr/lib/libalpm.so.15 /usr/lib/libalpm.so.14
```

**Comment by ChangqingW** [comment]
Reinstalling from source resolved the issue for me.
```
sudo pacman -R yay-bin
sudo pacman -S --needed git base-devel && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si
```

Edit: Pointed out by @merschformann , I forgot to include the debug package, you need to remove it as well if you have them:
```
sudo pacman -R yay-bin yay-bin-debug
sudo pacman -S --needed git base-devel && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si
```

**Comment by 69keks** [comment]
I just had this issue. Apparently `pacman -F` shows `libalpm.so.14` is already a part of pacman v7 but I can't find it in the system and the new pacman uses `libalpm v15` Temporarily symlinking or using git version would be the goto for now but I'll be simply waiting for the yay's update so it's cleanly fixed.

**Comment by arahiko-ayami** [comment]
Tried rebuild from source and it couldn't fix in my case. Symlink is still a possible temporary fix

**Comment by pdenapo** [comment]
This does not happen if you use the lastest git version (at commit commit 675f0ba3f3d4bbc006a12c29e273df0f4f533edc)

You can use the package yay-git

https://aur.archlinux.org/packages/yay-git

Perhaps a new release of yay will fix this!

**Comment by scorpius2k1** [comment]
> Reinstalling from source resolved the issue for me.
> 
> ```
> sudo pacman -R yay-bin
> sudo pacman -S --needed git base-devel && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si
> ```

On Arch Linux, can confirm a simple reinstall of yay worked for me as well (AFTER running a system update since there is a new version of pacman). This also worked for the source build version of 'yay' (instead of yay-bin), and using libalpm v15.0 and pacman v7.0.0.

`yay -V`
> yay v12.3.5 - libalpm v15.0.0

**Comment by 69keks** [comment]
> > Reinstalling from source resolved the issue for me.
> > ```
> > sudo pacman -R yay-bin
> > sudo pacman -S --needed git base-devel && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si
> > ```
> 
> On Arch Linux, can confirm a simple reinstall of yay worked for me as well (AFTER running a system update since there is a new version of pacman). This also worked for the source build version of 'yay' (instead of yay-bin), and using libalpm v15.0 and pacman v7.0.0.
> 
> `yay -V`
> 
> > yay v12.3.5 - libalpm v15.0.0

Then I guess it's just a classic package manager moment.. pacman updated before yay haha. OK, thanks.

**Comment by Jguer** [comment]
I usually push a simultaneous update of yay as pacman to ensure the two get updated on the same run but the github actions release flow for yay is having some issues with a deprecated action. 

I'll push just a pkgver bump meanwhile to ensure people updating now get a yay rebuild at the same time

**Comment by GildedHonour** [comment]
> Tried rebuild from source and it couldn't fix in my case. Symlink is still a possible temporary fix

Hehehe
But I've rebuilt it

**Comment by Venage5603** [comment]
this fixed the issue for me
![image](https://github.com/user-attachments/assets/17ae63b1-c67f-4392-ab3d-39d395fb4d6f)

**Comment by v1993** [comment]
While building from source with libalpm 15 works, it's worth noting that there's currently a known issue with it: #2500. That said, it's probably preferable to having yay not working at all, and without working yay AUR packages won't get updated automatically either way.

**Comment by moheladwy** [comment]
> This happened to me after an upgrade of pacman

Same with me

**Comment by moheladwy** [comment]
> While building from source with libalpm 15 works, it's worth noting that there's currently a known issue with it: #2500. That said, it's probably preferable to having yay not working at all, and without working yay AUR packages won't get updated automatically either way.

I think they have to upgrade the libalpm.so.14 dependency to libalpm.so.15 as this library has been upgraded while upgrading pacman.

**Comment by NathanPendergrast** [comment]
Cleanbuild the git repo of yay if you're having problems, it solved the issue for me.
`makepkg -Cf && makepkg -si`
If you run this in the git repo it should fix the problem.

**Comment by sudopluto** [comment]
since #2500 means that aur updates dont work anyways, here's the simlink approach if you dont want to reinstall yay just for a temp fix that doesnt fully work
`
sudo ln -sr /lib/libalpm.so.15 /lib/libalpm.so.14
`

**Comment by degoeym** [comment]
I also ran into the following while attempting to remove and rebuild/reinstall yay:

```
error: failed to commit transaction (conflicting files)
yay-debug: /usr/lib/debug/usr/bin/yay.debug exists in filesystem (owned by yay-bin-debug)
```

I simply moved to that directory and renamed the file `yay.debug.old`, then ran `makepkg -si` from the `yay` directory again and the install completed with yay being usable again. Just used it to upgrade Zoom.

**Comment by moheladwy** [comment]
> Cleanbuild the git repo of yay if you're having problems, it solved the issue for me. `makepkg -Cf && makepkg -si` If you run this in the git repo it should fix the problem.

I tried this solution and worked for me like a charm :+1:  :100:

**Comment by NathanPendergrast** [comment]
> since #2500 means that aur updates dont work anyways, here's the simlink approach if you dont want to reinstall yay just for a temp fix that doesnt fully work `sudo ln -sr /lib/libalpm.so.15 /lib/libalpm.so.14`

I would not recommend symlinking shared library files as a means of temp patching, it's trying to cure a symptom at the end of the day. A cleanbuild appears to be fixing most user's problems and should only take a few minutes.

**Comment by lands39** [comment]
just went through this fiasco, yay-bin seems broken but yay-git works normally. also had the same issue as @degoeym and after deleting that file, i could install the git version.

**Comment by merschformann** [comment]
> Reinstalling from source resolved the issue for me.
> 
> ```
> sudo pacman -R yay-bin
> sudo pacman -S --needed git base-devel && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si
> ```

I had to also remove the debug symbol package (I suppose renaming like mentioned above would have also worked).
Apart from a small modification for removing the other package, your solution worked well. Thank you! :hugs: 

Here is what I ran, just for reference:

```bash
sudo pacman -R yay-bin yay-bin-debug
sudo pacman -S --needed git base-devel && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si
```

**Comment by TheGamerCanine** [comment]
Reinstalling the binary did not seem to do it for me, even after uninstalling and rebuilding a few times I'm getting the exact same message when trying to update my AUR packages via yay. Although uninstalling the binary and building from source instead seemed to do the trick fine.

**Comment by Neo-29** [comment]
Binary needs an update
git (from source) is ok

**Comment by mowael01** [comment]
I think this error was due to incorrect go programming language installation. try installing it and then build yay again.

**Comment by fsxitutu** [comment]
Compile pacman v6.1.0 from source and copy libalpm.so.14 to /usr/lib .
Then execute
```shell
ldconfig
```

**Comment by BastionNtB** [comment]
> > Reinstalling from source resolved the issue for me.
> > ```
> > sudo pacman -R yay-bin
> > sudo pacman -S --needed git base-devel && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si
> > ```
> 
> I had to also remove the debug symbol package (I suppose renaming like mentioned above would have also worked). Apart from a small modification for removing the other package, your solution worked well. Thank you! 🤗
> 
> Here is what I ran, just for reference:
> 
> ```shell
> sudo pacman -R yay-bin yay-bin-debug
> sudo pacman -S --needed git base-devel && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si
> ```

Just so everyone knows, this is the ONLY workaround needed for this, you don't need to do any copying of libraries or symlinking. Just delete the current yay and rebuild from git.

**Comment by fsxitutu** [comment]
> > > Reinstalling from source resolved the issue for me.
> > > ```
> > > sudo pacman -R yay-bin
> > > sudo pacman -S --needed git base-devel && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si
> > > ```
> > 
> > 
> > I had to also remove the debug symbol package (I suppose renaming like mentioned above would have also worked). Apart from a small modification for removing the other package, your solution worked well. Thank you! 🤗
> > Here is what I ran, just for reference:
> > ```shell
> > sudo pacman -R yay-bin yay-bin-debug
> > sudo pacman -S --needed git base-devel && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si
> > ```
> 
> Just so everyone knows, this is the ONLY workaround needed for this, you don't need to do any copying of libraries or symlinking. Just delete the current yay and rebuild from git.

But this is not a user-friendly solution. Compiling yay-git requires a lot of disk, memory and CPU (compared to compiling pacman, which is much cheaper). That's why yay-bin is used.
Having both libalpm.so.15 and libalpm.so.14 in the system (instead of soft linking libalpm.so.14 to libalpm.so.15 or copying libalpm.so.15 to libalpm.so.14) does not affect the system in any way. They have different SONAMEs, and pacman and yay-bin will load them correctly when running.

**Comment by Jguer** [comment]
Issues with the builders are fixed, https://github.com/Jguer/yay/releases/tag/v12.4.1 has been released with all architectures compiled and AUR has been updated. I've also added a small note on the delay. 

The binaries present in the release are always compiled in the github actions so the archive checksum can be verified (avoid local tampering of binary packages).

I've never automated the pushing to the AUR of releases as I feel if the action is compromised it could be easily used for malware distribution and I also sign the AUR commits with my gpg key (except in this case where I'm not on my device).

I'm closing this issue, if you notice any follow up issues with this release don't hesitate to open a new one if it doesn't already exist

**Comment by alexandrosomegas** [comment]
I'm seek of this...

> sudo pacman -R yay
> warning: a52dec: unknown key '%INSTALLED_DB%' in local database
> warning: abseil-cpp: unknown key '%INSTALLED_DB%' in local database
> warning: accerciser: unknown key '%INSTALLED_DB%' in local database
> warning: accountsservice: unknown key '%INSTALLED_DB%' in local database
> warning: ack: unknown key '%INSTALLED_DB%' in local database
> warning: acl: unknown key '%INSTALLED_DB%' in local database
> warning: adobe-source-code-pro-fonts: unknown key '%INSTALLED_DB%' in local database
> warning: adwaita-cursors: unknown key '%INSTALLED_DB%' in local database
> ...
> warning: zsh-completions: unknown key '%INSTALLED_DB%' in local database
> warning: zstd: unknown key '%INSTALLED_DB%' in local database
> warning: zvbi: unknown key '%INSTALLED_DB%' in local database
> warning: zxing-cpp: unknown key '%INSTALLED_DB%' in local database
> error: target not found: yay
>

**Comment by doa379** [comment]
Terrible. Check out the litany of hacks here for "hacky" distro.

**Comment by pablodz** [comment]
Still happening

**Comment by fillman86** [comment]
still happening with yay, pamac, pacman, and paru. So I don't think it's just yay

**Comment by v1993** [comment]
> still happening with yay, pamac, pacman, and paru. So I don't think it's just yay

It's not "still happening", it's that libalpm got another version bump yesterday and the tools using it need a rebuild. I'm surprised it's happening with pacman itself, though - seems like a result of a partial upgrade.

**Comment by fillman86** [comment]
> > still happening with yay, pamac, pacman, and paru. So I don't think it's just yay
> 
> It's not "still happening", it's that libalpm got another version bump yesterday and the tools using it need a rebuild. I'm surprised it's happening with pacman itself, though - seems like a result of a partial upgrade.

I did a bit of looking, and I removed pamac. This caused many odd behaviours, but pacman was finally able to update, and I just reinstalled pamac from yay (which I also had to reinstall). I think the gist is that pamac doesn't like pacman updating, and causes a lockdown of updates
